### ISSUE TITLE
Blocked script execution

### ISSUE THREAD

**Issue by ssabchew** [jenkinsci/dashboard-view-plugin#318]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Add a iframe Portlet, and point it to a file in workspace: https://jenkins.com/view/all/job/generate_html/lastSuccessfulBuild/execution/node/3/ws/index.html

Where we have a java script that we want to be executed.

### Expected Results

Execute a java script

### Actual Results

Blocked script execution in 'https://jenkins.com/view/all/job/generate_html/lastSuccessfulBuild/execution/node/3/ws/index.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

### Anything else?

Script execution is enabled `/usr/bin/java -Dhudson.model.DirectoryBrowserSupport.CSP=  -Djava.awt.headless=true`

**Comment by TobiX** [comment]
This is not a bug, but a hardening method against [SECURITY-2559](https://www.jenkins.io/security/advisory/2022-03-15/#SECURITY-2559), see https://github.com/jenkinsci/dashboard-view-plugin/commit/d8bbd6dd93dcd9861b3aa689e036290a478f2406. You can set one of the system properties mentioned in the security advisory to get around this restriction. If you need more fine-grained control over the sandboxing, pull requests are always welcome.
